### ISSUE TITLE
panics when struct that shadows another struct is passed in

### ISSUE THREAD

**Issue by chr0n1x** [shwoodard/jsonapi#1]
Panics @ line `126` of `response.go` (out of index error on `modelValue.Field(i)`)

Example code:

```
type A struct {
    AString string `jsonapi:"attr,aString"`
}

type B struct {
    A
    BString string `jsonapi:"attr,bString"`
}
```

**Comment by shwoodard** [comment]
Looking into this.

**Comment by shwoodard** [comment]
Fixed by https://github.com/shwoodard/jsonapi/issues/2

**Comment by shwoodard** [comment]
@chr0n1x Can I get an lgtm?

**Comment by chr0n1x** [comment]
@shwoodard looks GREAT to me. Thanks for the quick patch & work! :D
