### ISSUE TITLE
Bad JSON panics

### ISSUE THREAD

**Issue by dustinsmith1024** [shwoodard/jsonapi#10]
I am about half way converting my API over to JSON-API compliant. Thanks so much for getting this project going.

In my testing, it seems JSON passed in without a `data` attribute throws a `runtime error: invalid memory address or nil pointer dereference` error.  I think the library should handle this and pass back an error rather than panicking. 

I played with how to do this a bit and it is pretty easy to add a nil check and return an error around https://github.com/shwoodard/jsonapi/blob/master/request.go#L63.  However that would give some potentially noncompliant results when a `{"data": null}` is actually expected.  It looks like it's possible on updates.  http://jsonapi.org/format/#crud-updating-relationships

Maybe I am overthinking this since my server go routine would just fail and 500 to the consumer, but I don't think the server should panic every time someone sends in non JSON-API compliant JSON.

I played around in a brach to see if I could fix it quickly.  The only idea I had was to use `unmarshal` vs `decode` and test the JSON if it actually had a `Data` attribute.

https://github.com/dustinsmith1024/jsonapi/commit/0659da44f95ad35344dea7b129e484da092b6026

**Comment by dustinsmith1024** [comment]
After looking a bit more into how the json package handles decoding errors, it might be appropriate to have a defer/recover block that catches these issues and returns and error to the consumer.

https://github.com/golang/go/blob/master/src/encoding/json/decode.go#L141

**Comment by shwoodard** [comment]
@dustinsmith1024 +1 `recover` pattern.  Can you send a PR?

**Comment by dustinsmith1024** [comment]
Yea, I should be able to work on it tomorrow.

**Comment by shwoodard** [comment]
Fixed in https://github.com/shwoodard/jsonapi/pull/13
