### ISSUE TITLE
Option to omit include from marshal

### ISSUE THREAD

**Issue by sweco-secfha** [shwoodard/jsonapi#18]
I think it should be possible to omit include. I have been using MarshalOnePayloadEmbedded, but it's an ugly workaround and doesn't work for MarshalMany.

**Comment by shwoodard** [comment]
Don't want more arguments to the interface

**Comment by sweco-secfha** [comment]
Why would you want to always include everything?
Lets say I have an item with 100 images attached to it, I wouldn't want to fetch all images (and data) when I fetch my item.
