### ISSUE TITLE
Date format, Unix time only?

### ISSUE THREAD

**Issue by proc** [shwoodard/jsonapi#22]
It seems this package only supports serializing date fields as unix time, but we have other consumers of the API that rely on a different format.  Why force a strict format? I was able to fix this with a patch... but there should be a better way.

**Comment by shwoodard** [comment]
This is in the jsonapi spec

**Comment by jayjzheng** [comment]
http://jsonapi.org/recommendations/#date-and-time-fields

> Although JSON API does not specify the format of date and time fields, it is recommended that servers align with ISO 8601. This W3C NOTE provides an overview of the recommended formats.

seems that it's only "recommended", not a "must" have.

**Comment by aren55555** [comment]
IMO the correct way to handle this would be via the StructField API. Perhaps something along the lines of:
```go
CreatedAt  *time.Time `jsonapi:"attr,updated-at,ISO8601"`
```

For backwards compatibility this would still have to produce a Unix Epoch integer time in the resultant JSON:
```go
CreatedAt  *time.Time `jsonapi:"attr,updated-at"`
```

**Comment by eelkeh** [comment]
Having the same issue, what would a patch look like?

**Comment by aren55555** [comment]
@jayjzheng @eelkeh 

So I've spent some time looking into this; Go's [time](https://golang.org/pkg/time/) package does not seem to support ISO 8601 out of the box. Furthermore the json package seems to by default marshall/unmarshall times in RFC 3339 format:

```
package main

import (
	"encoding/json"
	"fmt"
	"time"
)

func main() {
	data, _ := json.Marshal(time.Now())
	fmt.Println(string(data))
}
```
https://play.golang.org/p/fm-i07NKDX

**Comment by ki4jnq** [comment]
I'd like to add for anyone else who lands here that the annotation to unmarshal ISO8601 is lower-cased. So use `iso8601` instead of `ISO8601`.

Thanks for the awesome library!
