### ISSUE TITLE
Panic recovery -> reflect: call of reflect.Value.Elem on struct Value

### ISSUE THREAD

**Issue by basco-johnkevin** [shwoodard/jsonapi#25]
I'm getting this error: `panic recovery -> reflect: call of reflect.Value.Elem on struct Value` when using MarshalMany() method.

Here's the code:
```
type League2 struct {
    ID   int64  `json:"id jsonapi:"primary,leagues"`
    Name string `jsonapi:"attr,name"`
}

var leagues []model.League2

err := Db.Table("league").Find(&leagues).Error
if err != nil {
    c.JSON(http.StatusInternalServerError, gin.H{})
    return
}

leagueInterface := make([]interface{}, len(leagues))
for i, league := range leagues {
    leagueInterface[i] = league
}

leagues2, err := jsonapi.MarshalMany(leagueInterface)
```

Any idea why?

I'm using gin framework and gorm btw.

**Comment by sharonjl** [comment]
It is because you are using int64 as the Id type. I think support for it was dropped in the latest version in the refactoring. I submitted a patch to include it back again, #26.

**Comment by basco-johnkevin** [comment]
@sharonjl Thanks! It now works :+1: :)

**Comment by shwoodard** [comment]
https://github.com/shwoodard/jsonapi/pull/26 fixes.
