### ISSUE TITLE
Can't get relation to work

### ISSUE THREAD

**Issue by yfr** [shwoodard/jsonapi#7]
I have this setup. I read from a json file with has the defaults. Can you see whats wrong? I can see that in `UnmarshalPayload` after the decode the relation values are not decoded to `payload`.

```
package model

type Get struct {
	Id      int      `jsonapi:"primary,get"`
	Title   string   `jsonapi:"attr,title"`
	Status  string   `jsonapi:"attr,status"`
	Success *Success `jsonapi:"relation,success"`
}

type Success struct {
	Id         string `jsonapi:"primary,success"`
	Systemtime int `jsonapi:"attr,systemtime"`
}
```
```
{
  "data": {
    "type": "get",
    "id": "1",
    "attributes": {
      "title": "title2",
      "status": "OK",
      "success": {
        "status": "OK",
        "systemtime": "1378304936929",
      }
    }
  }
}
```

**Comment by shwoodard** [comment]
Yes, see the spec wrt to relationships.

http://jsonapi.org/format/#document-resource-object-relationships

Essentially, you're json should look like this,

```
{
  "data": {
    "type": "get",
    "id": "1",
    "attributes": {
      "title": "title2",
      "status": "OK"
    }, //attributes
    "relationships": {
        "success": {
          "data": {
            "id": "1",
            "type": "success"
            "attributes": {
              "status": "OK",
              "systemtime": "1378304936929",
            } // attributes
         }  // data
      }  // success
    }  // relationships
  } // data
}  // top
```

Also, your `Success` struct has no field, `status`.  Alternatively, you could sideload the data if your data has already been saved, and hence has real ids or you are generating client ids or uuids.  See the example on the homepage of http://jsonapi.org/ @ the `included` key and notice how it links up `type` and `id` to the realtionships above.

**Comment by yfr** [comment]
Thanks for explaining! Did not quite get the jsonapi docs.

On 3 August 2015 at 16:23, Sam Woodard <notifications@github.com> wrote:

> Yes, see the spec wrt to relationships.
>
> http://jsonapi.org/format/#document-resource-object-relationships
>
> Essentially, you're json should look like this,
>
> {
>   "data": {
>     "type": "get",
>     "id": "1",
>     "attributes": {
>       "title": "title2",
>       "status": "OK"
>     }, //attributes
>     "relationships": {
>         "success": {
>           "data": {
>             "id": "1",
>             "type": "success"
>             "attributes": {
>               "status": "OK",
>               "systemtime": "1378304936929",
>             } // attributes
>          }  // data
>       }  // success
>     }  // relationships
>   } // data
> }  // top
>
> Also, your Success struct has no field, status. Alternatively, you could
> sideload the data if your data has already been saved, and hence has real
> ids or you are generating client ids or uuids. See the example on the
> homepage of http://jsonapi.org/ @ the included key and notice how it
> links up type and id to the realtionships above.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/shwoodard/jsonapi/issues/7#issuecomment-127259651>.
>



-- 
--
Frank Mecklenburg
mecklenburg@ubilabs.net

Ubilabs GmbH
Juliusstr. 25
22769 Hamburg, Germany

Telefon +49 40 - 60 94 661 - 0
Fax +49 40 - 60 94 661 - 66

Handelsregister Hamburg: HRB 110269
Steuernummer: 46/765/01253


Geschäftsführer: Michael Pletziger, Jens Wille

--
