### ISSUE TITLE
ID's (ints) showing as strings in JSON

### ISSUE THREAD

**Issue by dustinsmith1024** [shwoodard/jsonapi#8]
I noticed my ID's which are of int type are showing as strings in the marshaled JSON.  I am guessing this is known, because of this test https://github.com/shwoodard/jsonapi/blob/master/response_test.go#L77.  

Just checking if this is intended?

**Comment by shwoodard** [comment]
Yes.  The jsonapi spec specifies strings for ids.

**Comment by aren55555** [comment]
@dustinsmith1024 http://jsonapi.org/format/#document-resource-object-identification states:

"Every resource object MUST contain an id member and a type member. The values of the id and type members MUST be strings."

**Comment by dustinsmith1024** [comment]
Thanks. I just skimmed over that part when reviewing the spec.
